export function generateCompletion(shell: string): string {
  if (shell.includes("zsh")) return zshCompletion();
  if (shell.includes("pwsh") || shell.includes("powershell"))
    return powershellCompletion();
  return bashCompletion();
}

function bashCompletion(): string {
  return [
    "# alloy bash completion — 添加到 ~/.bashrc 或 ~/.bash_profile:",
    "#   source <(alloy completion bash)",
    "",
    "_alloy_completion() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    "",
    "  if [ \"$COMP_CWORD\" -eq 1 ]; then",
    '    COMPREPLY=($(compgen -W "-v --version -h --help init status doctor update completion" -- "$cur"))',
    "    return 0",
    "  fi",
    "",
    '  case "${COMP_WORDS[1]}" in',
    "    init)",
    '      COMPREPLY=($(compgen -W "--scope --inject-claude-md --help -h" -- "$cur"))',
    "      ;;",
    "    status|doctor)",
    '      COMPREPLY=($(compgen -W "--json --help -h" -- "$cur"))',
    "      ;;",
    "    update)",
    '      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))',
    "      ;;",
    "    completion)",
    '      COMPREPLY=($(compgen -W "bash zsh pwsh powershell" -- "$cur"))',
    "      ;;",
    "  esac",
    "}",
    "",
    "complete -F _alloy_completion alloy",
    "",
  ].join("\n");
}

function zshCompletion(): string {
  return [
    "# alloy zsh completion — 添加到 ~/.zshrc:",
    "#   source <(alloy completion zsh)",
    "",
    "#compdef alloy",
    "",
    "_alloy_commands() {",
    "  local -a cmds",
    "  cmds=(",
    "    'init:项目初始化——检测环境 → 安装依赖 → 部署 schema + skill'",
    "    'status:查看所有活跃 change 总览'",
    "    'doctor:诊断——版本兼容性、文件一致性'",
    "    'update:更新 Alloy skill 文件到最新版'",
    "    'completion:生成 shell 补全脚本'",
    "  )",
    "  _describe 'command' cmds",
    "}",
    "",
    "_alloy() {",
    "  local context state state_descr line",
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
    "    '{-v,--version}[显示版本号]' \\",
    "    '{-h,--help}[显示帮助]' \\",
    "    '1: :_alloy_commands' \\",
    "    '*:: :->args'",
    "",
    "  case $state in",
    "    args)",
    "      case $words[1] in",
    "        init)",
    "          _arguments \\",
    "            '--scope[安装范围]:scope:(project global)' \\",
    "            '--inject-claude-md[注入 CLAUDE.md]' \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "        status|doctor)",
    "          _arguments \\",
    "            '--json[JSON 格式输出]' \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "        update|completion)",
    "          _arguments \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "      esac",
    "      ;;",
    "  esac",
    "}",
    "",
    "_alloy",
    "",
  ].join("\n");
}

function powershellCompletion(): string {
  return [
    "# alloy PowerShell completion",
    "# 添加到 PowerShell profile:",
    "#   alloy completion pwsh | Out-File -FilePath $PROFILE -Append",
    "",
    "Register-ArgumentCompleter -Native -CommandName alloy -ScriptBlock {",
    "  param($wordToComplete, $commandAst, $cursorPosition)",
    "",
    "  $commands = @('init', 'status', 'doctor', 'update', 'completion')",
    "  $globalOpts = @('--version', '-v', '--help', '-h')",
    "",
    "  $tokens = $commandAst.CommandElements",
    "  $command = $null",
    "",
    "  foreach ($token in $tokens) {",
    "    $value = $token.Value",
    "    if ($value -in $commands) {",
    "      $command = $value",
    "    }",
    "  }",
    "",
    "  if (-not $command) {",
    "    $completionText = @()",
    "    foreach ($cmd in $commands) {",
    '      if ($cmd -like "$wordToComplete*") { $completionText += $cmd }',
    "    }",
    "    foreach ($opt in $globalOpts) {",
    '      if ($opt -like "$wordToComplete*") { $completionText += $opt }',
    "    }",
    "    $completionText | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }",
    "    return",
    "  }",
    "",
    "  $opts = @()",
    "  switch ($command) {",
    "    'init'    { $opts = @('--scope', '--inject-claude-md', '--help', '-h') }",
    "    'status'  { $opts = @('--json', '--help', '-h') }",
    "    'doctor'  { $opts = @('--json', '--help', '-h') }",
    "    'update'  { $opts = @('--help', '-h') }",
    "    'completion' { $opts = @('bash', 'zsh', 'pwsh', 'powershell', '--help', '-h') }",
    "  }",
    "",
    "  $opts | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {",
    "    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
    "  }",
    "}",
    "",
  ].join("\n");
}
