export function generateCompletion(shell: string): string {
  if (shell.includes("zsh")) return zshCompletion();
  return bashCompletion();
}

function bashCompletion(): string {
  return [
    "# alloy bash completion — 添加到 ~/.bashrc 或 ~/.bash_profile:",
    "#   source <(alloy completion)",
    "",
    "_alloy_completion() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    "",
    "  if [ \"$COMP_CWORD\" -eq 1 ]; then",
    '    COMPREPLY=($(compgen -W "init status doctor update completion" -- "$cur"))',
    "    return 0",
    "  fi",
    "",
    '  case "${COMP_WORDS[1]}" in',
    "    init)",
    '      COMPREPLY=($(compgen -W "--scope --inject-claude-md --help -h" -- "$cur"))',
    "      ;;",
    "    status|doctor)",
    '      COMPREPLY=($(compgen -W "--json --help -h" -- "$cur"))',
    "      ;;",
    "    update)",
    '      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))',
    "      ;;",
    "    completion)",
    '      COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))',
    "      ;;",
    "  esac",
    "}",
    "",
    "complete -F _alloy_completion alloy",
    "",
  ].join("\n");
}

function zshCompletion(): string {
  return [
    "# alloy zsh completion — 添加到 ~/.zshrc:",
    "#   source <(alloy completion)",
    "",
    "#compdef alloy",
    "",
    "_alloy_commands() {",
    "  local -a cmds",
    "  cmds=(",
    "    'init:项目初始化——检测环境 → 安装依赖 → 部署 schema + skill'",
    "    'status:查看所有活跃 change 总览'",
    "    'doctor:诊断——版本兼容性、文件一致性'",
    "    'update:更新 Alloy skill 文件到最新版'",
    "    'completion:生成 shell 补全脚本'",
    "  )",
    "  _describe 'command' cmds",
    "}",
    "",
    "_alloy() {",
    "  local context state state_descr line",
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
    "    '--version[显示版本号]' \\",
    "    '{-h,--help}[显示帮助]' \\",
    "    '1: :_alloy_commands' \\",
    "    '*:: :->args'",
    "",
    "  case $state in",
    "    args)",
    "      case $words[1] in",
    "        init)",
    "          _arguments \\",
    "            '--scope[安装范围]:scope:(project global)' \\",
    "            '--inject-claude-md[注入 CLAUDE.md]' \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "        status|doctor)",
    "          _arguments \\",
    "            '--json[JSON 格式输出]' \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "        update|completion)",
    "          _arguments \\",
    "            '{-h,--help}[显示帮助]'",
    "          ;;",
    "      esac",
    "      ;;",
    "  esac",
    "}",
    "",
    "_alloy",
    "",
  ].join("\n");
}
